
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class GetLatestReportDetailsParameters {
    /**
    * Label: Application ID, type: entry
    */
    String nexusApplicationId

    static GetLatestReportDetailsParameters initParameters(StepParameters sp) {
        GetLatestReportDetailsParameters parameters = new GetLatestReportDetailsParameters()

        def nexusApplicationId = sp.getRequiredParameter('nexusApplicationId').value
        parameters.nexusApplicationId = nexusApplicationId

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: cc8fc84dd04ea3bb1c7766a32ca45d30 ===
