
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class GetReportDetailsParameters {
    /**
    * Label: Application ID, type: entry
    */
    String nexusApplicationId
    /**
    * Label: Report ID, type: entry
    */
    String reportId

    static GetReportDetailsParameters initParameters(StepParameters sp) {
        GetReportDetailsParameters parameters = new GetReportDetailsParameters()

        def nexusApplicationId = sp.getRequiredParameter('nexusApplicationId').value
        parameters.nexusApplicationId = nexusApplicationId

        def reportId = sp.getRequiredParameter('reportId').value
        parameters.reportId = reportId

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: dc839981bf9cfb2b516c2d21f531a86e ===
