pluginInfo:
  # This is default sample specification
  # Feel free to change it
  # Call pdk showdoc pluginspec to see the list of available fields and their description
  pluginName: 'EC-NexusIQServer'
  version: '2.0.0'
  description: 'Integrates witn SonaType Nexus IQ Server reimplemented with PDK.'
  author: 'Shaohua Wen swen@cloudbees.com'
  supportUrl: 'none'
  category: 'Security'
  shell: 'ec-groovy'

# Plugin configuration description
configuration:
  # A script for checking connection will be generated
  checkConnection: 'true'
  # A set of fields will be added to process debug level in the configuration
  hasDebugLevel: true
  restConfigInfo:
    endpointLabel: 'Nexus IQ Server URL'
    endpointDescription: Specify the URL to the IQ Nexus server. e.g. http://nexus-iq-server:8070
    checkConnectionUri: '/api/v2/organizations'
    defaultEndpointValue: http://nexus-iq-server:8070
    headers:
      Accept: 'application/json'
    authSchemes:
      basic:
        userNameLabel: 'Username'
        passwordLabel: 'Password'
        description: 'Username and password to connect to ...'
  hasProxySupport: false
  parameters:
  -
    name: nexusJavaLocation
    documentation: Full path to java binary or a command that should be used as java. If not set "java" will be used.
    required: false
    type: entry
    label: Java Location
  -
    name: nexusCLILocation
    documentation: Specify the absolute path to the IQ Nexus CLI. For example /opt/DevSecOps/nexus-iq-cli-1.47.0-01.jar
    required: true
    type: entry
    label: Nexus CLI Location

restClient:
  userAgent: My Nexus IQ Client
  language: groovy
  endpoints:
    - methodName: getReportDetails
      httpMethod: GET
      parameters:
        - name: applicationId
          in: path
        - name: reportId
          in: path
      url: /api/v2/applications/{{applicationId}}/reports/{{reportId}}

procedures:
-
  name: 'Create Build Report'
  description: 'This procedure creates a build report using the Nexus CLI.'
  # configuration field will be generated automatically
  hasConfig: true
  parameters:
  -
    name: nexusApplicationId
    documentation: The name of the Application for which Build Report needs to be created. For example sandbox-application.
    required: true
    type: entry
    label: Application ID
  -
    name: nexusApplicationWarLocation
    documentation: Specify the absolute path to the Application WAR file. For example /opt/DevSecOps/struts2-rest-showcase-*.war
    required: true
    type: entry
    label: Application WAR Location
  outputParameters:
  -
    # Output parameter name
    name: Violation Summary
    # Output parameter description
    description: 'Something like this "Summary of policy violations: 7 critical, 3 severe, 0 moderate"'
  -
    # Output parameter name
    name: Build Report URL
    # Output parameter description
    description: 'Path to Build Report URL. Something like this http://nexus/ui/links/application/sandbox-application/report/806fbab9e4ed426e85e1a7ee721b0e6f'
  -
    # Output parameter name
    name: Critical Violation Count
    # Output parameter description
    description: Number of Critical Violations, for example 7
  -
    # Output parameter name
    name: Severe Violation Count
    # Output parameter description
    description: Number of Severe Violations, for example 3
  -
    # Output parameter name
    name: Moderate Violation Count
    # Output parameter description
    description: Number of Moderate Violations, for example 0
  -
    # Output parameter name
    name: Component Count
    # Output parameter description
    description: Number of Components Identified, for example 28
  -
    # Output parameter name
    name: Security Issue Count
    # Output parameter description
    description: Number of Security Issues Identified, for example 27
  -
    # Output parameter name
    name: License Issue Count
    # Output parameter description
    description: Number of License Issues Identified, for example 6
